name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn clean package --batch-mode --update-snapshots verify
      - name: Create .jar file
        uses: actions/upload-artifact@v3
        with:
         name: ScenarioQualityCheckerApp
         path: target/*.jar
  notify:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3 
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions - build failure!
          body: Build of ${{github.repository}} FAILED! Please check the logs!
          to: wiktoria.bialasik05@gmail.com, chojniakkatarzyna@protonmail.com, mati.czechow@gmail.com
          from: Luke Skywalker
          
          
